# Generated by Django 4.0 on 2022-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tokenId',
            field=models.CharField(max_length=65),
        ),
    ]
