# Generated by Django 4.0 on 2022-02-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_token_tokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxhackuser',
            name='claimedTokens',
            field=models.ManyToManyField(related_name='claimedTokens', to='api.Token'),
        ),
    ]
