# Generated by Django 4.0 on 2022-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_oxhackuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='contractAddress',
        ),
        migrations.AlterField(
            model_name='oxhackuser',
            name='claimedTokens',
            field=models.ManyToManyField(blank=True, related_name='claimedTokens', to='api.Token'),
        ),
        migrations.AlterField(
            model_name='oxhackuser',
            name='tokens',
            field=models.ManyToManyField(blank=True, to='api.Token'),
        ),
    ]
