import Head from 'next/head'
import { Text } from '@chakra-ui/react'

import { Container, Hero, Footer } from '../components'

const Index = () => (
  <Container height="100vh">
    <Head>
      <title>OxHack22</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Hero />

    <Footer>
      <Text>Made in Oxford ❤️</Text>
    </Footer>
  </Container>
)

export default Index
